object Versions {
    const val facebook = "8.0.0"
    const val firebaseUi = "7.2.0"
    const val firebaseAuth = "22.0.0"
    const val googeServices = "4.3.15"
    const val serialization = "1.4.1"
    const val navVersion = "2.6.0"
    const val room = "2.5.1"
    const val build = "8.0.2"
    const val jvmTarget = "18"
    const val core = "1.10.1"
    const val appCompat = "1.6.1"
    const val material = "1.9.0"
    const val constraintLayout = "2.1.4"
    const val jUnit = "4.13.2"
    const val ext = "1.1.5"
    const val espresso = "3.5.1"
    const val kotlin = "1.8.22"
    const val splashScreen = "1.0.1"
    const val navigation = "2.6.0"
    const val glide = "4.15.1"
    const val koin = "3.4.2"
    const val retrofit = "2.9.0"
    const val okHttp = "4.11.0"
    const val gson = "2.9.0"
    const val paging = "3.1.1"
}